#!/bin/sh

PASSWD=$(dd if=/dev/mtdblock2 bs=1 skip=65036 count=16 2>/dev/null)
if [ `expr length "$PASSWD"` != 0 ]; then
  ( echo "$PASSWD"; sleep 1; echo "$PASSWD" ) | passwd root
else
  ( echo "admin"; sleep 1; echo "admin" ) | passwd root
fi

exit 0
