#!/bin/sh /etc/rc.common

EXTRA_COMMANDS="lucistat"
EXTRA_HELP="lucistat  Get status information if lua friendly format"

lucistat() {
  cat /tmp/wibe_luci
}

boot() {
  return 0
}

start() {
  /sbin/start-stop-daemon -S -b -m -p /var/run/umtsd-sh.pid -x /usr/share/umtsd/umtsd.sh
}

stop() {
  /sbin/start-stop-daemon -K -p /var/run/umtsd-sh.pid
  sleep 1
  /sbin/start-stop-daemon -K -x /sbin/umtsd
}
